export const actionTypes = {
    LOGOUT_USER: 'LOGOUT_USER',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_FAIL: 'LOGOUT_USER_FAIL',
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    SEND_RECOVERY_EMAIL: 'SEND_RECOVERY_EMAIL',
    SEND_RECOVERY_EMAIL_FAIL: 'SEND_RECOVERY_EMAIL_FAIL',
    SEND_RECOVERY_EMAIL_SUCCESS: 'SEND_RECOVERY_EMAIL_SUCCESS',
    VERIFY_EMAIL: 'VERIFY_EMAIL',
    VERIFY_EMAIL_FAIL: 'VERIFY_EMAIL_FAIL',
    VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
    
    FINISHED_MISSION: 'FINISHED_MISSION',
    NEW_STARTING_MISSION: 'NEW_STARTING_MISSION'
};